### PR TITLE
Changed the silly names for Warp X and Warp Y

### PR DESCRIPTION
**Pull request by Decoder0007**
warp x angle -> warp x
warp y angle -> warp y

### CODE REVIEW

**Comment by FlowVix** [comment]
i feel like this isn't as descriptive, those properties do actually represent the angle of the basis vectors for warping

**Comment by Decoder0007** [comment]
So does the rotation but it's not called rotation_angle

**Comment by FlowVix** [comment]
...what else can you measure rotation in but angle

**Comment by Decoder0007** [comment]
What else can you measure warp x and warp y in but angle

**Comment by FlowVix** [comment]
shear factor? skew factor? it's not immediately obvious that a linear transformation is represented using angle

**Pull request closed without merging**
